[package]
name = "sample-tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
psutil = "3"

[dependencies.clap]
version = "4"
features = ["derive"]
